version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb
        environment:
          DISPLAY: ":99"
          GOOGLE_APPLICATION_CREDENTIALS: "/root/gcloud-service-key.json"

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: setup GCP
          command: echo $GCLOUD_SERVICE_KEY | base64 -d > /root/gcloud-service-key.json
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn screenshot
      - run: yarn regression